In [34]:
import numpy as np

A = np.array([[1, 1, 1, 1],
              [2, -1, 3, 4],
              [-3, 2, -2, 5],
              [1, -1, 4, -1]])

b = np.array([10, 8, -3, 5])

solution = np.linalg.solve(A, b)

print("Solution:")
print(f"x = {solution[0]:.4f}")
print(f"y = {solution[1]:.4f}")
print(f"z = {solution[2]:.4f}")
print(f"w = {solution[3]:.4f}")


Solution:
x = 3.4434
y = 4.6981
z = 1.6226
w = 0.2358


In [30]:
## NUMBER 1

import numpy as np

A = np.array([
    [1, 1, 1, 1],
    [2, -1, 3, 4],
    [-3, 2, -2, 5],
    [1, -1, 4, -1]
])

b = np.array([10, 8, -3, 5])

print("Augmented Matrix [A|b]:")
augmented_matrix = np.column_stack((A, b))
print(augmented_matrix)


Augmented Matrix [A|b]:
[[ 1  1  1  1 10]
 [ 2 -1  3  4  8]
 [-3  2 -2  5 -3]
 [ 1 -1  4 -1  5]]


In [31]:
A[1] = A[1] - 2 * A[0]
b[1] = b[1] - 2 * b[0]

A[2] = A[2] + 3 * A[0]
b[2] = b[2] + 3 * b[0]

A[3] = A[3] - A[0]
b[3] = b[3] - b[0]

# Display the updated augmented matrix
print("\nAfter eliminating x-terms:")
augmented_matrix = np.column_stack((A, b))
print(augmented_matrix)


After eliminating x-terms:
[[  1   1   1   1  10]
 [  0  -3   1   2 -12]
 [  0   5   1   8  27]
 [  0  -2   3  -2  -5]]


In [32]:
A[2] = A[2] - (5/3) * A[1]
b[2] = b[2] - (5/3) * b[1]

A[3] = A[3] - (2/3) * A[1]
b[3] = b[3] - (2/3) * b[1]

# Display the updated augmented matrix
print("\nAfter eliminating y-terms:")
augmented_matrix = np.column_stack((A, b))
print(augmented_matrix)


After eliminating y-terms:
[[  1   1   1   1  10]
 [  0  -3   1   2 -12]
 [  0  10   0   4  47]
 [  0   0   2  -3   3]]


In [29]:
w = b[3] / A[3][3]
z = (b[2] - A[2][3] * w) / A[2][2]
y = (b[1] - A[1][2] * z - A[1][3] * w) / A[1][1]
x = (b[0] - A[0][1] * y - A[0][2] * z - A[0][3] * w) / A[0][0]

# Output the solution
print("\nSolution:")
print(f"x = {x:.4f}")
print(f"y = {y:.4f}")
print(f"z = {z:.4f}")
print(f"w = {w:.4f}")


Solution:
x = -inf
y = inf
z = inf
w = -1.0000


C:\Users\dtjab\AppData\Local\Temp\ipykernel_6936\1099005645.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  z = (b[2] - A[2][3] * w) / A[2][2]


In [47]:
i = np.array([[1500, -600,0], [0,600,900], [1,1, -1]]) 
v = np.array ([12,15,0])

cur = np.linalg.solve (i, v)

i1, i2, i3 = cur 

print (i1,i2,i3)
print ((i1*1500)-(i2*600))
print ((i2*600)+(i3*900))

0.00967741935483871 0.004193548387096773 0.013870967741935485
12.000000000000002
15.0


In [49]:

A = np.array([[2,1,3], [1,2,1], [3,1,2]])
A_inv = np.linalg.inv(A)
A_inv


array([[-0.375, -0.125,  0.625],
       [-0.125,  0.625, -0.125],
       [ 0.625, -0.125, -0.375]])